"""Build the llamadart DecisionEngine parity fixture from official laya 0.3.5 reference rows.

Adds, per row, the exact tokenizer inputs (head text, option texts, state text) so the Dart
sequence builder can be tested with a lookup tokenizer and no model file.

Usage: python gen_decision_fixture.py ROWS.json TOKENIZER_DIR OUT.json
"""
import json, sys
from transformers import AutoTokenizer
from laya.agent import Agent
from laya.common import render_options, serialize_state

ref = json.load(open(sys.argv[1]))
tok = AutoTokenizer.from_pretrained(sys.argv[2])
mask = tok.mask_token
pieces = {}

def ids(text):
    if text not in pieces:
        pieces[text] = tok(text, add_special_tokens=False)["input_ids"]
    return pieces[text]

for row in ref["rows"]:
    q = Agent._to_internal(row["question"])
    ids("%s question: %s" % (q["t"], str(q["ins"]).replace(mask, " ")))
    for o in render_options(q):
        ids(" " + o.replace(mask, " "))
    ids(serialize_state(row["state"]).replace(mask, " "))

out = {
    "source": "laya %s (convaiinnovations/laya), fp32 CPU, generated by gen_decision_fixture.py" % ref["laya"],
    "specialTokens": {"cls": tok.cls_token_id, "sep": tok.sep_token_id, "pad": tok.pad_token_id, "mask": tok.mask_token_id},
    "temperature": ref["temperature"],
    "temperatureByOptions": ref["temperature_by_options"],
    "rows": [{
        "id": r["id"], "state": r["state"], "question": r["question"], "ids": r["ids"], "markers": r["markers"],
        "rawLogits": r["raw_logits"], "rawActLogits": r["raw_act_logits"], "answer": r["answer"],
    } for r in ref["rows"]],
    "pieces": pieces,
}
json.dump(out, open(sys.argv[3], "w"), ensure_ascii=False, separators=(",", ":"))
print(len(out["rows"]), "rows,", len(pieces), "pieces")
