/// Raw llama.cpp, ggml and mtmd FFI bindings, generated by ffigen.
///
/// **Outside semantic versioning.** These mirror the C API of the bundled
/// llama.cpp build, so any release that updates llama.cpp can rename, change
/// or remove them. Prefer `package:llamadart/llamadart.dart`.
///
/// Native platforms only. On Web this library exposes a few stubs that throw
/// [UnsupportedError].
library;

export 'src/backends/llama_cpp/bindings_stub.dart'
    if (dart.library.io) 'src/backends/llama_cpp/bindings.dart';
