// coverage:ignore-file
// ignore_for_file: always_specify_types, unused_field
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
/// @nodoc

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:llamadart/stable_diffusion')
library;

import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<adetailer_ctx_t>,
    ffi.Pointer<sd_ctx_t>,
    sd_image_t,
    ffi.Pointer<sd_adetailer_params_t>,
    ffi.Pointer<sd_img_gen_params_t>,
    ffi.Pointer<ffi.Pointer<sd_image_t>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external bool adetail_image(
  ffi.Pointer<adetailer_ctx_t> adetailer_ctx,
  ffi.Pointer<sd_ctx_t> sd_ctx,
  sd_image_t input_image,
  ffi.Pointer<sd_adetailer_params_t> adetailer_params,
  ffi.Pointer<sd_img_gen_params_t> inpaint_params,
  ffi.Pointer<ffi.Pointer<sd_image_t>> images_out,
  ffi.Pointer<ffi.Int> num_images_out,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
  )
>(symbol: 'convert')
external bool _convert(
  ffi.Pointer<ffi.Char> input_path,
  ffi.Pointer<ffi.Char> vae_path,
  ffi.Pointer<ffi.Char> output_path,
  int output_type,
  ffi.Pointer<ffi.Char> tensor_type_rules,
  bool convert_name,
);

bool convert(
  ffi.Pointer<ffi.Char> input_path,
  ffi.Pointer<ffi.Char> vae_path,
  ffi.Pointer<ffi.Char> output_path,
  sd_type_t output_type,
  ffi.Pointer<ffi.Char> tensor_type_rules,
  bool convert_name,
) {
  return _convert(
    input_path,
    vae_path,
    output_path,
    output_type.value,
    tensor_type_rules,
    convert_name,
  );
}

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.UnsignedInt,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Int,
  )
>(symbol: 'convert_with_components')
external bool _convert_with_components(
  ffi.Pointer<ffi.Char> model_path,
  ffi.Pointer<ffi.Char> clip_l_path,
  ffi.Pointer<ffi.Char> clip_g_path,
  ffi.Pointer<ffi.Char> t5xxl_path,
  ffi.Pointer<ffi.Char> diffusion_model_path,
  ffi.Pointer<ffi.Char> vae_path,
  ffi.Pointer<ffi.Char> output_path,
  int output_type,
  ffi.Pointer<ffi.Char> tensor_type_rules,
  bool convert_name,
  int n_threads,
);

bool convert_with_components(
  ffi.Pointer<ffi.Char> model_path,
  ffi.Pointer<ffi.Char> clip_l_path,
  ffi.Pointer<ffi.Char> clip_g_path,
  ffi.Pointer<ffi.Char> t5xxl_path,
  ffi.Pointer<ffi.Char> diffusion_model_path,
  ffi.Pointer<ffi.Char> vae_path,
  ffi.Pointer<ffi.Char> output_path,
  sd_type_t output_type,
  ffi.Pointer<ffi.Char> tensor_type_rules,
  bool convert_name,
  int n_threads,
) {
  return _convert_with_components(
    model_path,
    clip_l_path,
    clip_g_path,
    t5xxl_path,
    diffusion_model_path,
    vae_path,
    output_path,
    output_type.value,
    tensor_type_rules,
    convert_name,
    n_threads,
  );
}

@ffi.Native<ffi.Void Function()>()
external void disable_imatrix_collection();

@ffi.Native<ffi.Void Function()>()
external void enable_imatrix_collection();

@ffi.Native<ffi.Void Function(ffi.Pointer<adetailer_ctx_t>)>()
external void free_adetailer_ctx(ffi.Pointer<adetailer_ctx_t> adetailer_ctx);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_audio_t>)>()
external void free_sd_audio(ffi.Pointer<sd_audio_t> audio);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_ctx_t>)>()
external void free_sd_ctx(ffi.Pointer<sd_ctx_t> sd_ctx);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_image_t>, ffi.Int)>()
external void free_sd_images(
  ffi.Pointer<sd_image_t> result_images,
  int num_images,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<upscaler_ctx_t>)>()
external void free_upscaler_ctx(ffi.Pointer<upscaler_ctx_t> upscaler_ctx);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<sd_ctx_t>,
    ffi.Pointer<sd_img_gen_params_t>,
    ffi.Pointer<ffi.Pointer<sd_image_t>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external bool generate_image(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  ffi.Pointer<sd_img_gen_params_t> sd_img_gen_params,
  ffi.Pointer<ffi.Pointer<sd_image_t>> images_out,
  ffi.Pointer<ffi.Int> num_images_out,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<sd_ctx_t>,
    ffi.Pointer<sd_vid_gen_params_t>,
    ffi.Pointer<ffi.Pointer<sd_image_t>>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Pointer<sd_audio_t>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external bool generate_video(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  ffi.Pointer<sd_vid_gen_params_t> sd_vid_gen_params,
  ffi.Pointer<ffi.Pointer<sd_image_t>> frames_out,
  ffi.Pointer<ffi.Int> num_frames_out,
  ffi.Pointer<ffi.Pointer<sd_audio_t>> audio_out,
  ffi.Pointer<ffi.Int> fps_out,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<upscaler_ctx_t>)>()
external int get_upscale_factor(ffi.Pointer<upscaler_ctx_t> upscaler_ctx);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int get_upscaler_model_scale(ffi.Pointer<ffi.Char> model_path);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Char>)>()
external bool load_imatrix(ffi.Pointer<ffi.Char> imatrix_path);

@ffi.Native<
  ffi.Pointer<adetailer_ctx_t> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<adetailer_ctx_t> new_adetailer_ctx(
  ffi.Pointer<ffi.Char> detector_path,
  int n_threads,
  ffi.Pointer<ffi.Char> backend,
  ffi.Pointer<ffi.Char> params_backend,
);

@ffi.Native<ffi.Pointer<sd_ctx_t> Function(ffi.Pointer<sd_ctx_params_t>)>()
external ffi.Pointer<sd_ctx_t> new_sd_ctx(
  ffi.Pointer<sd_ctx_params_t> sd_ctx_params,
);

@ffi.Native<
  ffi.Pointer<upscaler_ctx_t> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Int,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<upscaler_ctx_t> new_upscaler_ctx(
  ffi.Pointer<ffi.Char> esrgan_path,
  bool direct,
  int n_threads,
  int tile_size,
  ffi.Pointer<ffi.Char> backend,
  ffi.Pointer<ffi.Char> params_backend,
);

@ffi.Native<
  ffi.Bool Function(
    sd_image_t,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Bool,
  )
>()
external bool preprocess_canny(
  sd_image_t image,
  double high_threshold,
  double low_threshold,
  double weak,
  double strong,
  bool inverse,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void save_imatrix(ffi.Pointer<ffi.Char> imatrix_path);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_cache_params_t>)>()
external void sd_cache_params_init(ffi.Pointer<sd_cache_params_t> cache_params);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_ctx_t>, ffi.UnsignedInt)>(
  symbol: 'sd_cancel_generation',
)
external void _sd_cancel_generation(ffi.Pointer<sd_ctx_t> sd_ctx, int mode);

void sd_cancel_generation(ffi.Pointer<sd_ctx_t> sd_ctx, sd_cancel_mode_t mode) {
  return _sd_cancel_generation(sd_ctx, mode.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> sd_commit();

@ffi.Native<ffi.Bool Function(ffi.Pointer<sd_ctx_t>)>()
external bool sd_ctx_has_control_net(ffi.Pointer<sd_ctx_t> sd_ctx);

@ffi.Native<ffi.Bool Function(ffi.Pointer<sd_ctx_t>, ffi.Pointer<ffi.Char>)>()
external bool sd_ctx_load_control_net(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_ctx_params_t>)>()
external void sd_ctx_params_init(ffi.Pointer<sd_ctx_params_t> sd_ctx_params);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sd_ctx_params_t>)>()
external ffi.Pointer<ffi.Char> sd_ctx_params_to_str(
  ffi.Pointer<sd_ctx_params_t> sd_ctx_params,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<sd_ctx_t>)>()
external bool sd_ctx_supports_image_generation(ffi.Pointer<sd_ctx_t> sd_ctx);

@ffi.Native<ffi.Bool Function(ffi.Pointer<sd_ctx_t>)>()
external bool sd_ctx_supports_video_generation(ffi.Pointer<sd_ctx_t> sd_ctx);

@ffi.Native<ffi.Bool Function(ffi.Pointer<sd_ctx_t>)>()
external bool sd_ctx_unload_control_net(ffi.Pointer<sd_ctx_t> sd_ctx);

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_ctx_t>, ffi.UnsignedInt)>(
  symbol: 'sd_dart_cancel_generation',
)
external void _sd_dart_cancel_generation(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  int mode,
);

void sd_dart_cancel_generation(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  sd_cancel_mode_t mode,
) {
  return _sd_dart_cancel_generation(sd_ctx, mode.value);
}

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void sd_dart_exit_free(ffi.Pointer<ffi.Void> object);

@ffi.Native<ffi.Void Function(ffi.Int32, ffi.Int32)>()
external void sd_dart_exit_set_wait_ms(int wait_ms, int work_wait_ms);

@ffi.Native<ffi.Int32 Function()>()
external int sd_dart_exit_tracked_count();

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<sd_ctx_t>,
    ffi.Pointer<sd_img_gen_params_t>,
    ffi.Pointer<ffi.Pointer<sd_image_t>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external bool sd_dart_generate_image(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  ffi.Pointer<sd_img_gen_params_t> sd_img_gen_params,
  ffi.Pointer<ffi.Pointer<sd_image_t>> images_out,
  ffi.Pointer<ffi.Int> num_images_out,
);

@ffi.Native<ffi.Int32 Function()>()
external int sd_dart_gpu_device_count();

@ffi.Native<
  ffi.Int32 Function(ffi.Int32, ffi.Pointer<sd_dart_gpu_device_memory_t>)
>()
external int sd_dart_gpu_device_memory(
  int device_index,
  ffi.Pointer<sd_dart_gpu_device_memory_t> out,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external int sd_dart_last_error(ffi.Pointer<ffi.Char> text, int capacity);

@ffi.Native<ffi.Uint64 Function()>()
external int sd_dart_log_dropped();

@ffi.Native<ffi.Void Function()>()
external void sd_dart_log_enable();

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Int32>,
    ffi.Pointer<ffi.Size>,
  )
>()
external int sd_dart_log_read(
  int after,
  ffi.Pointer<ffi.Char> text,
  int capacity,
  ffi.Pointer<ffi.Int32> level,
  ffi.Pointer<ffi.Size> length,
);

@ffi.Native<ffi.Void Function(ffi.Int32)>()
external void sd_dart_log_set_level(int level);

@ffi.Native<ffi.Pointer<sd_ctx_t> Function(ffi.Pointer<sd_ctx_params_t>)>()
external ffi.Pointer<sd_ctx_t> sd_dart_new_sd_ctx(
  ffi.Pointer<sd_ctx_params_t> sd_ctx_params,
);

@ffi.Native<ffi.Void Function()>()
external void sd_dart_progress_enable();

@ffi.Native<
  ffi.Size Function(
    ffi.Uint64,
    ffi.Pointer<sd_dart_progress_t>,
    ffi.Size,
    ffi.Pointer<ffi.Uint64>,
  )
>(isLeaf: true)
external int sd_dart_progress_read(
  int after,
  ffi.Pointer<sd_dart_progress_t> reports,
  int capacity,
  ffi.Pointer<ffi.Uint64> latest,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<sd_ctx_t>)>(
  symbol: 'sd_get_default_sample_method',
)
external int _sd_get_default_sample_method(ffi.Pointer<sd_ctx_t> sd_ctx);

sample_method_t sd_get_default_sample_method(ffi.Pointer<sd_ctx_t> sd_ctx) {
  return sample_method_t.fromValue(_sd_get_default_sample_method(sd_ctx));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<sd_ctx_t>, ffi.UnsignedInt)>(
  symbol: 'sd_get_default_scheduler',
)
external int _sd_get_default_scheduler(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  int sample_method,
);

scheduler_t sd_get_default_scheduler(
  ffi.Pointer<sd_ctx_t> sd_ctx,
  sample_method_t sample_method,
) {
  return scheduler_t.fromValue(
    _sd_get_default_scheduler(sd_ctx, sample_method.value),
  );
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sd_ctx_t>)>()
external ffi.Pointer<ffi.Char> sd_get_model_version_name(
  ffi.Pointer<sd_ctx_t> sd_ctx,
);

@ffi.Native<ffi.Int32 Function()>()
external int sd_get_num_physical_cores();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> sd_get_system_info();

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_hires_params_t>)>()
external void sd_hires_params_init(ffi.Pointer<sd_hires_params_t> hires_params);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_hires_upscaler_name',
)
external ffi.Pointer<ffi.Char> _sd_hires_upscaler_name(int upscaler);

ffi.Pointer<ffi.Char> sd_hires_upscaler_name(sd_hires_upscaler_t upscaler) {
  return _sd_hires_upscaler_name(upscaler.value);
}

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_img_gen_params_t>)>()
external void sd_img_gen_params_init(
  ffi.Pointer<sd_img_gen_params_t> sd_img_gen_params,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sd_img_gen_params_t>)>()
external ffi.Pointer<ffi.Char> sd_img_gen_params_to_str(
  ffi.Pointer<sd_img_gen_params_t> sd_img_gen_params,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<ffi.Char>, ffi.Size)>()
external int sd_list_devices(ffi.Pointer<ffi.Char> buffer, int buffer_size);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_lora_apply_mode_name',
)
external ffi.Pointer<ffi.Char> _sd_lora_apply_mode_name(int mode);

ffi.Pointer<ffi.Char> sd_lora_apply_mode_name(lora_apply_mode_t mode) {
  return _sd_lora_apply_mode_name(mode.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_prediction_name',
)
external ffi.Pointer<ffi.Char> _sd_prediction_name(int prediction);

ffi.Pointer<ffi.Char> sd_prediction_name(prediction_t prediction) {
  return _sd_prediction_name(prediction.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_preview_name',
)
external ffi.Pointer<ffi.Char> _sd_preview_name(int preview);

ffi.Pointer<ffi.Char> sd_preview_name(preview_t preview) {
  return _sd_preview_name(preview.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_rng_type_name',
)
external ffi.Pointer<ffi.Char> _sd_rng_type_name(int rng_type);

ffi.Pointer<ffi.Char> sd_rng_type_name(rng_type_t rng_type) {
  return _sd_rng_type_name(rng_type.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_sample_method_name',
)
external ffi.Pointer<ffi.Char> _sd_sample_method_name(int sample_method);

ffi.Pointer<ffi.Char> sd_sample_method_name(sample_method_t sample_method) {
  return _sd_sample_method_name(sample_method.value);
}

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_sample_params_t>)>()
external void sd_sample_params_init(
  ffi.Pointer<sd_sample_params_t> sample_params,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<sd_sample_params_t>)>()
external ffi.Pointer<ffi.Char> sd_sample_params_to_str(
  ffi.Pointer<sd_sample_params_t> sample_params,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_scheduler_name',
)
external ffi.Pointer<ffi.Char> _sd_scheduler_name(int scheduler);

ffi.Pointer<ffi.Char> sd_scheduler_name(scheduler_t scheduler) {
  return _sd_scheduler_name(scheduler.value);
}

@ffi.Native<
  ffi.Void Function(sd_graph_eval_callback_t, ffi.Pointer<ffi.Void>)
>()
external void sd_set_backend_eval_callback(
  sd_graph_eval_callback_t cb,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<ffi.Void Function(sd_log_cb_t, ffi.Pointer<ffi.Void>)>()
external void sd_set_log_callback(
  sd_log_cb_t sd_log_cb,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<
  ffi.Void Function(
    sd_preview_cb_t,
    ffi.UnsignedInt,
    ffi.Int,
    ffi.Bool,
    ffi.Bool,
    ffi.Pointer<ffi.Void>,
  )
>(symbol: 'sd_set_preview_callback')
external void _sd_set_preview_callback(
  sd_preview_cb_t cb,
  int mode,
  int interval,
  bool denoised,
  bool noisy,
  ffi.Pointer<ffi.Void> data,
);

void sd_set_preview_callback(
  sd_preview_cb_t cb,
  preview_t mode,
  int interval,
  bool denoised,
  bool noisy,
  ffi.Pointer<ffi.Void> data,
) {
  return _sd_set_preview_callback(
    cb,
    mode.value,
    interval,
    denoised,
    noisy,
    data,
  );
}

@ffi.Native<ffi.Void Function(sd_progress_cb_t, ffi.Pointer<ffi.Void>)>()
external void sd_set_progress_callback(
  sd_progress_cb_t cb,
  ffi.Pointer<ffi.Void> data,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'sd_type_name',
)
external ffi.Pointer<ffi.Char> _sd_type_name(int type);

ffi.Pointer<ffi.Char> sd_type_name(sd_type_t type) {
  return _sd_type_name(type.value);
}

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> sd_version();

@ffi.Native<ffi.Void Function(ffi.Pointer<sd_vid_gen_params_t>)>()
external void sd_vid_gen_params_init(
  ffi.Pointer<sd_vid_gen_params_t> sd_vid_gen_params,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_lora_apply_mode',
)
external int _str_to_lora_apply_mode(ffi.Pointer<ffi.Char> str);

lora_apply_mode_t str_to_lora_apply_mode(ffi.Pointer<ffi.Char> str) {
  return lora_apply_mode_t.fromValue(_str_to_lora_apply_mode(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_prediction',
)
external int _str_to_prediction(ffi.Pointer<ffi.Char> str);

prediction_t str_to_prediction(ffi.Pointer<ffi.Char> str) {
  return prediction_t.fromValue(_str_to_prediction(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_preview',
)
external int _str_to_preview(ffi.Pointer<ffi.Char> str);

preview_t str_to_preview(ffi.Pointer<ffi.Char> str) {
  return preview_t.fromValue(_str_to_preview(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_rng_type',
)
external int _str_to_rng_type(ffi.Pointer<ffi.Char> str);

rng_type_t str_to_rng_type(ffi.Pointer<ffi.Char> str) {
  return rng_type_t.fromValue(_str_to_rng_type(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_sample_method',
)
external int _str_to_sample_method(ffi.Pointer<ffi.Char> str);

sample_method_t str_to_sample_method(ffi.Pointer<ffi.Char> str) {
  return sample_method_t.fromValue(_str_to_sample_method(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_scheduler',
)
external int _str_to_scheduler(ffi.Pointer<ffi.Char> str);

scheduler_t str_to_scheduler(ffi.Pointer<ffi.Char> str) {
  return scheduler_t.fromValue(_str_to_scheduler(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_sd_hires_upscaler',
)
external int _str_to_sd_hires_upscaler(ffi.Pointer<ffi.Char> str);

sd_hires_upscaler_t str_to_sd_hires_upscaler(ffi.Pointer<ffi.Char> str) {
  return sd_hires_upscaler_t.fromValue(_str_to_sd_hires_upscaler(str));
}

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'str_to_sd_type',
)
external int _str_to_sd_type(ffi.Pointer<ffi.Char> str);

sd_type_t str_to_sd_type(ffi.Pointer<ffi.Char> str) {
  return sd_type_t.fromValue(_str_to_sd_type(str));
}

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<upscaler_ctx_t>,
    sd_image_t,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<sd_image_t>>,
    ffi.Pointer<ffi.Int>,
  )
>()
external bool upscale(
  ffi.Pointer<upscaler_ctx_t> upscaler_ctx,
  sd_image_t input_image,
  int upscale_factor,
  ffi.Pointer<ffi.Pointer<sd_image_t>> images_out,
  ffi.Pointer<ffi.Int> num_images_out,
);

const int SD_DART_GPU_DEFAULT_DEVICE = -1;

const int SD_DART_LOG_TEXT_SIZE = 4096;

final class adetailer_ctx_t extends ffi.Opaque {}

final class ggml_tensor extends ffi.Opaque {}

enum lora_apply_mode_t {
  LORA_APPLY_AUTO(0),
  LORA_APPLY_IMMEDIATELY(1),
  LORA_APPLY_AT_RUNTIME(2),
  LORA_APPLY_MODE_COUNT(3);

  final int value;
  const lora_apply_mode_t(this.value);

  static lora_apply_mode_t fromValue(int value) => switch (value) {
    0 => LORA_APPLY_AUTO,
    1 => LORA_APPLY_IMMEDIATELY,
    2 => LORA_APPLY_AT_RUNTIME,
    3 => LORA_APPLY_MODE_COUNT,
    _ => throw ArgumentError('Unknown value for lora_apply_mode_t: $value'),
  };
}

enum prediction_t {
  EPS_PRED(0),
  V_PRED(1),
  EDM_V_PRED(2),
  FLOW_PRED(3),
  FLUX_FLOW_PRED(4),
  SEFI_FLOW_PRED(5),
  MINIT2I_FLOW_PRED(6),
  SENSENOVA_U1_FLOW_PRED(7),
  PREDICTION_COUNT(8);

  final int value;
  const prediction_t(this.value);

  static prediction_t fromValue(int value) => switch (value) {
    0 => EPS_PRED,
    1 => V_PRED,
    2 => EDM_V_PRED,
    3 => FLOW_PRED,
    4 => FLUX_FLOW_PRED,
    5 => SEFI_FLOW_PRED,
    6 => MINIT2I_FLOW_PRED,
    7 => SENSENOVA_U1_FLOW_PRED,
    8 => PREDICTION_COUNT,
    _ => throw ArgumentError('Unknown value for prediction_t: $value'),
  };
}

enum preview_t {
  PREVIEW_NONE(0),
  PREVIEW_PROJ(1),
  PREVIEW_TAE(2),
  PREVIEW_VAE(3),
  PREVIEW_COUNT(4);

  final int value;
  const preview_t(this.value);

  static preview_t fromValue(int value) => switch (value) {
    0 => PREVIEW_NONE,
    1 => PREVIEW_PROJ,
    2 => PREVIEW_TAE,
    3 => PREVIEW_VAE,
    4 => PREVIEW_COUNT,
    _ => throw ArgumentError('Unknown value for preview_t: $value'),
  };
}

enum rng_type_t {
  STD_DEFAULT_RNG(0),
  CUDA_RNG(1),
  CPU_RNG(2),
  RNG_TYPE_COUNT(3);

  final int value;
  const rng_type_t(this.value);

  static rng_type_t fromValue(int value) => switch (value) {
    0 => STD_DEFAULT_RNG,
    1 => CUDA_RNG,
    2 => CPU_RNG,
    3 => RNG_TYPE_COUNT,
    _ => throw ArgumentError('Unknown value for rng_type_t: $value'),
  };
}

enum sample_method_t {
  EULER_SAMPLE_METHOD(0),
  EULER_A_SAMPLE_METHOD(1),
  HEUN_SAMPLE_METHOD(2),
  DPM2_SAMPLE_METHOD(3),
  DPMPP2S_A_SAMPLE_METHOD(4),
  DPMPP2M_SAMPLE_METHOD(5),
  DPMPP2Mv2_SAMPLE_METHOD(6),
  IPNDM_SAMPLE_METHOD(7),
  IPNDM_V_SAMPLE_METHOD(8),
  LCM_SAMPLE_METHOD(9),
  DDIM_TRAILING_SAMPLE_METHOD(10),
  TCD_SAMPLE_METHOD(11),
  RES_MULTISTEP_SAMPLE_METHOD(12),
  RES_2S_SAMPLE_METHOD(13),
  ER_SDE_SAMPLE_METHOD(14),
  EULER_CFG_PP_SAMPLE_METHOD(15),
  EULER_A_CFG_PP_SAMPLE_METHOD(16),
  EULER_GE_SAMPLE_METHOD(17),
  DPMPP2M_SDE_SAMPLE_METHOD(18),
  DPMPP2M_SDE_BT_SAMPLE_METHOD(19),
  LMS_SAMPLE_METHOD(20),
  SAMPLE_METHOD_COUNT(21);

  final int value;
  const sample_method_t(this.value);

  static sample_method_t fromValue(int value) => switch (value) {
    0 => EULER_SAMPLE_METHOD,
    1 => EULER_A_SAMPLE_METHOD,
    2 => HEUN_SAMPLE_METHOD,
    3 => DPM2_SAMPLE_METHOD,
    4 => DPMPP2S_A_SAMPLE_METHOD,
    5 => DPMPP2M_SAMPLE_METHOD,
    6 => DPMPP2Mv2_SAMPLE_METHOD,
    7 => IPNDM_SAMPLE_METHOD,
    8 => IPNDM_V_SAMPLE_METHOD,
    9 => LCM_SAMPLE_METHOD,
    10 => DDIM_TRAILING_SAMPLE_METHOD,
    11 => TCD_SAMPLE_METHOD,
    12 => RES_MULTISTEP_SAMPLE_METHOD,
    13 => RES_2S_SAMPLE_METHOD,
    14 => ER_SDE_SAMPLE_METHOD,
    15 => EULER_CFG_PP_SAMPLE_METHOD,
    16 => EULER_A_CFG_PP_SAMPLE_METHOD,
    17 => EULER_GE_SAMPLE_METHOD,
    18 => DPMPP2M_SDE_SAMPLE_METHOD,
    19 => DPMPP2M_SDE_BT_SAMPLE_METHOD,
    20 => LMS_SAMPLE_METHOD,
    21 => SAMPLE_METHOD_COUNT,
    _ => throw ArgumentError('Unknown value for sample_method_t: $value'),
  };
}

enum scheduler_t {
  DISCRETE_SCHEDULER(0),
  KARRAS_SCHEDULER(1),
  EXPONENTIAL_SCHEDULER(2),
  AYS_SCHEDULER(3),
  GITS_SCHEDULER(4),
  SGM_UNIFORM_SCHEDULER(5),
  SIMPLE_SCHEDULER(6),
  SMOOTHSTEP_SCHEDULER(7),
  KL_OPTIMAL_SCHEDULER(8),
  LCM_SCHEDULER(9),
  BONG_TANGENT_SCHEDULER(10),
  LTX2_SCHEDULER(11),
  LOGIT_NORMAL_SCHEDULER(12),
  FLUX2_SCHEDULER(13),
  FLUX_SCHEDULER(14),
  BETA_SCHEDULER(15),
  LLADA_IMAGE_SCHEDULER(16),
  SCHEDULER_COUNT(17);

  final int value;
  const scheduler_t(this.value);

  static scheduler_t fromValue(int value) => switch (value) {
    0 => DISCRETE_SCHEDULER,
    1 => KARRAS_SCHEDULER,
    2 => EXPONENTIAL_SCHEDULER,
    3 => AYS_SCHEDULER,
    4 => GITS_SCHEDULER,
    5 => SGM_UNIFORM_SCHEDULER,
    6 => SIMPLE_SCHEDULER,
    7 => SMOOTHSTEP_SCHEDULER,
    8 => KL_OPTIMAL_SCHEDULER,
    9 => LCM_SCHEDULER,
    10 => BONG_TANGENT_SCHEDULER,
    11 => LTX2_SCHEDULER,
    12 => LOGIT_NORMAL_SCHEDULER,
    13 => FLUX2_SCHEDULER,
    14 => FLUX_SCHEDULER,
    15 => BETA_SCHEDULER,
    16 => LLADA_IMAGE_SCHEDULER,
    17 => SCHEDULER_COUNT,
    _ => throw ArgumentError('Unknown value for scheduler_t: $value'),
  };
}

final class sd_adetailer_params_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> prompt;

  external ffi.Pointer<ffi.Char> negative_prompt;

  external ffi.Pointer<ffi.Char> extra_ad_args;

  static ffi.Pointer<sd_adetailer_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> prompt,
    required ffi.Pointer<ffi.Char> negative_prompt,
    required ffi.Pointer<ffi.Char> extra_ad_args,
  }) => $allocator<sd_adetailer_params_t>()
    ..ref.prompt = prompt
    ..ref.negative_prompt = negative_prompt
    ..ref.extra_ad_args = extra_ad_args;
}

final class sd_audio_t extends ffi.Struct {
  @ffi.Uint32()
  external int sample_rate;

  @ffi.Uint32()
  external int channels;

  @ffi.Uint64()
  external int sample_count;

  external ffi.Pointer<ffi.Float> data;

  static ffi.Pointer<sd_audio_t> $allocate(
    ffi.Allocator $allocator, {
    required int sample_rate,
    required int channels,
    required int sample_count,
    required ffi.Pointer<ffi.Float> data,
  }) => $allocator<sd_audio_t>()
    ..ref.sample_rate = sample_rate
    ..ref.channels = channels
    ..ref.sample_count = sample_count
    ..ref.data = data;
}

enum sd_cache_mode_t {
  SD_CACHE_DISABLED(0),
  SD_CACHE_EASYCACHE(1),
  SD_CACHE_UCACHE(2),
  SD_CACHE_DBCACHE(3),
  SD_CACHE_TAYLORSEER(4),
  SD_CACHE_CACHE_DIT(5),
  SD_CACHE_SPECTRUM(6);

  final int value;
  const sd_cache_mode_t(this.value);

  static sd_cache_mode_t fromValue(int value) => switch (value) {
    0 => SD_CACHE_DISABLED,
    1 => SD_CACHE_EASYCACHE,
    2 => SD_CACHE_UCACHE,
    3 => SD_CACHE_DBCACHE,
    4 => SD_CACHE_TAYLORSEER,
    5 => SD_CACHE_CACHE_DIT,
    6 => SD_CACHE_SPECTRUM,
    _ => throw ArgumentError('Unknown value for sd_cache_mode_t: $value'),
  };
}

final class sd_cache_params_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int modeAsInt;

  sd_cache_mode_t get mode => sd_cache_mode_t.fromValue(modeAsInt);
  set mode(sd_cache_mode_t value) => modeAsInt = value.value;

  @ffi.Float()
  external double reuse_threshold;

  @ffi.Float()
  external double start_percent;

  @ffi.Float()
  external double end_percent;

  @ffi.Float()
  external double error_decay_rate;

  @ffi.Bool()
  external bool use_relative_threshold;

  @ffi.Bool()
  external bool reset_error_on_compute;

  @ffi.Int()
  external int Fn_compute_blocks;

  @ffi.Int()
  external int Bn_compute_blocks;

  @ffi.Float()
  external double residual_diff_threshold;

  @ffi.Int()
  external int max_warmup_steps;

  @ffi.Int()
  external int max_cached_steps;

  @ffi.Int()
  external int max_continuous_cached_steps;

  @ffi.Int()
  external int taylorseer_n_derivatives;

  @ffi.Int()
  external int taylorseer_skip_interval;

  external ffi.Pointer<ffi.Char> scm_mask;

  @ffi.Bool()
  external bool scm_policy_dynamic;

  @ffi.Float()
  external double spectrum_w;

  @ffi.Int()
  external int spectrum_m;

  @ffi.Float()
  external double spectrum_lam;

  @ffi.Int()
  external int spectrum_window_size;

  @ffi.Float()
  external double spectrum_flex_window;

  @ffi.Int()
  external int spectrum_warmup_steps;

  @ffi.Float()
  external double spectrum_stop_percent;

  static ffi.Pointer<sd_cache_params_t> $allocate(
    ffi.Allocator $allocator, {
    required sd_cache_mode_t mode,
    required double reuse_threshold,
    required double start_percent,
    required double end_percent,
    required double error_decay_rate,
    required bool use_relative_threshold,
    required bool reset_error_on_compute,
    required int Fn_compute_blocks,
    required int Bn_compute_blocks,
    required double residual_diff_threshold,
    required int max_warmup_steps,
    required int max_cached_steps,
    required int max_continuous_cached_steps,
    required int taylorseer_n_derivatives,
    required int taylorseer_skip_interval,
    required ffi.Pointer<ffi.Char> scm_mask,
    required bool scm_policy_dynamic,
    required double spectrum_w,
    required int spectrum_m,
    required double spectrum_lam,
    required int spectrum_window_size,
    required double spectrum_flex_window,
    required int spectrum_warmup_steps,
    required double spectrum_stop_percent,
  }) => $allocator<sd_cache_params_t>()
    ..ref.mode = mode
    ..ref.reuse_threshold = reuse_threshold
    ..ref.start_percent = start_percent
    ..ref.end_percent = end_percent
    ..ref.error_decay_rate = error_decay_rate
    ..ref.use_relative_threshold = use_relative_threshold
    ..ref.reset_error_on_compute = reset_error_on_compute
    ..ref.Fn_compute_blocks = Fn_compute_blocks
    ..ref.Bn_compute_blocks = Bn_compute_blocks
    ..ref.residual_diff_threshold = residual_diff_threshold
    ..ref.max_warmup_steps = max_warmup_steps
    ..ref.max_cached_steps = max_cached_steps
    ..ref.max_continuous_cached_steps = max_continuous_cached_steps
    ..ref.taylorseer_n_derivatives = taylorseer_n_derivatives
    ..ref.taylorseer_skip_interval = taylorseer_skip_interval
    ..ref.scm_mask = scm_mask
    ..ref.scm_policy_dynamic = scm_policy_dynamic
    ..ref.spectrum_w = spectrum_w
    ..ref.spectrum_m = spectrum_m
    ..ref.spectrum_lam = spectrum_lam
    ..ref.spectrum_window_size = spectrum_window_size
    ..ref.spectrum_flex_window = spectrum_flex_window
    ..ref.spectrum_warmup_steps = spectrum_warmup_steps
    ..ref.spectrum_stop_percent = spectrum_stop_percent;
}

enum sd_cancel_mode_t {
  SD_CANCEL_ALL(0),
  SD_CANCEL_NEW_LATENTS(1),
  SD_CANCEL_RESET(2);

  final int value;
  const sd_cancel_mode_t(this.value);

  static sd_cancel_mode_t fromValue(int value) => switch (value) {
    0 => SD_CANCEL_ALL,
    1 => SD_CANCEL_NEW_LATENTS,
    2 => SD_CANCEL_RESET,
    _ => throw ArgumentError('Unknown value for sd_cancel_mode_t: $value'),
  };
}

final class sd_ctx_params_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> model_path;

  external ffi.Pointer<ffi.Char> clip_l_path;

  external ffi.Pointer<ffi.Char> clip_g_path;

  external ffi.Pointer<ffi.Char> clip_vision_path;

  external ffi.Pointer<ffi.Char> t5xxl_path;

  external ffi.Pointer<ffi.Char> llm_path;

  external ffi.Pointer<ffi.Char> llm_vision_path;

  external ffi.Pointer<ffi.Char> diffusion_model_path;

  external ffi.Pointer<ffi.Char> high_noise_diffusion_model_path;

  external ffi.Pointer<ffi.Char> uncond_diffusion_model_path;

  external ffi.Pointer<ffi.Char> embeddings_connectors_path;

  external ffi.Pointer<ffi.Char> vae_path;

  external ffi.Pointer<ffi.Char> audio_vae_path;

  external ffi.Pointer<ffi.Char> audio_encoder_path;

  external ffi.Pointer<ffi.Char> taesd_path;

  external ffi.Pointer<ffi.Char> control_net_path;

  external ffi.Pointer<ffi.Char> ip_adapter_path;

  external ffi.Pointer<ffi.Char> motion_module_path;

  external ffi.Pointer<sd_embedding_t> embeddings;

  @ffi.Uint32()
  external int embedding_count;

  external ffi.Pointer<ffi.Char> photo_maker_path;

  external ffi.Pointer<ffi.Char> pulid_weights_path;

  external ffi.Pointer<ffi.Char> tensor_type_rules;

  @ffi.Int()
  external int n_threads;

  @ffi.UnsignedInt()
  external int wtypeAsInt;

  sd_type_t get wtype => sd_type_t.fromValue(wtypeAsInt);
  set wtype(sd_type_t value) => wtypeAsInt = value.value;

  @ffi.UnsignedInt()
  external int rng_typeAsInt;

  rng_type_t get rng_type => rng_type_t.fromValue(rng_typeAsInt);
  set rng_type(rng_type_t value) => rng_typeAsInt = value.value;

  @ffi.UnsignedInt()
  external int sampler_rng_typeAsInt;

  rng_type_t get sampler_rng_type =>
      rng_type_t.fromValue(sampler_rng_typeAsInt);
  set sampler_rng_type(rng_type_t value) => sampler_rng_typeAsInt = value.value;

  @ffi.UnsignedInt()
  external int predictionAsInt;

  prediction_t get prediction => prediction_t.fromValue(predictionAsInt);
  set prediction(prediction_t value) => predictionAsInt = value.value;

  @ffi.UnsignedInt()
  external int lora_apply_modeAsInt;

  lora_apply_mode_t get lora_apply_mode =>
      lora_apply_mode_t.fromValue(lora_apply_modeAsInt);
  set lora_apply_mode(lora_apply_mode_t value) =>
      lora_apply_modeAsInt = value.value;

  @ffi.Bool()
  external bool enable_mmap;

  @ffi.Bool()
  external bool flash_attn;

  @ffi.Bool()
  external bool diffusion_flash_attn;

  @ffi.Bool()
  external bool tae_preview_only;

  @ffi.Bool()
  external bool diffusion_conv_direct;

  @ffi.Bool()
  external bool vae_conv_direct;

  @ffi.Bool()
  external bool force_sdxl_vae_conv_scale;

  @ffi.Int()
  external int vae_formatAsInt;

  sd_vae_format_t get vae_format => sd_vae_format_t.fromValue(vae_formatAsInt);
  set vae_format(sd_vae_format_t value) => vae_formatAsInt = value.value;

  external ffi.Pointer<ffi.Char> max_vram;

  @ffi.Bool()
  external bool disable_prefetch;

  @ffi.Bool()
  external bool eager_load;

  external ffi.Pointer<ffi.Char> backend;

  external ffi.Pointer<ffi.Char> params_backend;

  external ffi.Pointer<ffi.Char> split_mode;

  @ffi.Bool()
  external bool auto_fit;

  external ffi.Pointer<ffi.Char> rpc_servers;

  external ffi.Pointer<ffi.Char> model_args;

  @ffi.Bool()
  external bool disable_segmented_compute;

  @ffi.Float()
  external double linear_scale;

  @ffi.Float()
  external double attn_scale;

  external ffi.Pointer<ffi.Char> tokenizer;

  @ffi.Bool()
  external bool sage_attn;

  @ffi.Int()
  external int conditioning_cache_size;

  static ffi.Pointer<sd_ctx_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> model_path,
    required ffi.Pointer<ffi.Char> clip_l_path,
    required ffi.Pointer<ffi.Char> clip_g_path,
    required ffi.Pointer<ffi.Char> clip_vision_path,
    required ffi.Pointer<ffi.Char> t5xxl_path,
    required ffi.Pointer<ffi.Char> llm_path,
    required ffi.Pointer<ffi.Char> llm_vision_path,
    required ffi.Pointer<ffi.Char> diffusion_model_path,
    required ffi.Pointer<ffi.Char> high_noise_diffusion_model_path,
    required ffi.Pointer<ffi.Char> uncond_diffusion_model_path,
    required ffi.Pointer<ffi.Char> embeddings_connectors_path,
    required ffi.Pointer<ffi.Char> vae_path,
    required ffi.Pointer<ffi.Char> audio_vae_path,
    required ffi.Pointer<ffi.Char> audio_encoder_path,
    required ffi.Pointer<ffi.Char> taesd_path,
    required ffi.Pointer<ffi.Char> control_net_path,
    required ffi.Pointer<ffi.Char> ip_adapter_path,
    required ffi.Pointer<ffi.Char> motion_module_path,
    required ffi.Pointer<sd_embedding_t> embeddings,
    required int embedding_count,
    required ffi.Pointer<ffi.Char> photo_maker_path,
    required ffi.Pointer<ffi.Char> pulid_weights_path,
    required ffi.Pointer<ffi.Char> tensor_type_rules,
    required int n_threads,
    required sd_type_t wtype,
    required rng_type_t rng_type,
    required rng_type_t sampler_rng_type,
    required prediction_t prediction,
    required lora_apply_mode_t lora_apply_mode,
    required bool enable_mmap,
    required bool flash_attn,
    required bool diffusion_flash_attn,
    required bool tae_preview_only,
    required bool diffusion_conv_direct,
    required bool vae_conv_direct,
    required bool force_sdxl_vae_conv_scale,
    required sd_vae_format_t vae_format,
    required ffi.Pointer<ffi.Char> max_vram,
    required bool disable_prefetch,
    required bool eager_load,
    required ffi.Pointer<ffi.Char> backend,
    required ffi.Pointer<ffi.Char> params_backend,
    required ffi.Pointer<ffi.Char> split_mode,
    required bool auto_fit,
    required ffi.Pointer<ffi.Char> rpc_servers,
    required ffi.Pointer<ffi.Char> model_args,
    required bool disable_segmented_compute,
    required double linear_scale,
    required double attn_scale,
    required ffi.Pointer<ffi.Char> tokenizer,
    required bool sage_attn,
    required int conditioning_cache_size,
  }) => $allocator<sd_ctx_params_t>()
    ..ref.model_path = model_path
    ..ref.clip_l_path = clip_l_path
    ..ref.clip_g_path = clip_g_path
    ..ref.clip_vision_path = clip_vision_path
    ..ref.t5xxl_path = t5xxl_path
    ..ref.llm_path = llm_path
    ..ref.llm_vision_path = llm_vision_path
    ..ref.diffusion_model_path = diffusion_model_path
    ..ref.high_noise_diffusion_model_path = high_noise_diffusion_model_path
    ..ref.uncond_diffusion_model_path = uncond_diffusion_model_path
    ..ref.embeddings_connectors_path = embeddings_connectors_path
    ..ref.vae_path = vae_path
    ..ref.audio_vae_path = audio_vae_path
    ..ref.audio_encoder_path = audio_encoder_path
    ..ref.taesd_path = taesd_path
    ..ref.control_net_path = control_net_path
    ..ref.ip_adapter_path = ip_adapter_path
    ..ref.motion_module_path = motion_module_path
    ..ref.embeddings = embeddings
    ..ref.embedding_count = embedding_count
    ..ref.photo_maker_path = photo_maker_path
    ..ref.pulid_weights_path = pulid_weights_path
    ..ref.tensor_type_rules = tensor_type_rules
    ..ref.n_threads = n_threads
    ..ref.wtype = wtype
    ..ref.rng_type = rng_type
    ..ref.sampler_rng_type = sampler_rng_type
    ..ref.prediction = prediction
    ..ref.lora_apply_mode = lora_apply_mode
    ..ref.enable_mmap = enable_mmap
    ..ref.flash_attn = flash_attn
    ..ref.diffusion_flash_attn = diffusion_flash_attn
    ..ref.tae_preview_only = tae_preview_only
    ..ref.diffusion_conv_direct = diffusion_conv_direct
    ..ref.vae_conv_direct = vae_conv_direct
    ..ref.force_sdxl_vae_conv_scale = force_sdxl_vae_conv_scale
    ..ref.vae_format = vae_format
    ..ref.max_vram = max_vram
    ..ref.disable_prefetch = disable_prefetch
    ..ref.eager_load = eager_load
    ..ref.backend = backend
    ..ref.params_backend = params_backend
    ..ref.split_mode = split_mode
    ..ref.auto_fit = auto_fit
    ..ref.rpc_servers = rpc_servers
    ..ref.model_args = model_args
    ..ref.disable_segmented_compute = disable_segmented_compute
    ..ref.linear_scale = linear_scale
    ..ref.attn_scale = attn_scale
    ..ref.tokenizer = tokenizer
    ..ref.sage_attn = sage_attn
    ..ref.conditioning_cache_size = conditioning_cache_size;
}

final class sd_ctx_t extends ffi.Opaque {}

enum sd_dart_exit_stage {
  SD_DART_EXIT_STAGE_CONTEXT_USER(0),
  SD_DART_EXIT_STAGE_CONTEXT(1),
  SD_DART_EXIT_STAGE_RESOURCE(2);

  final int value;
  const sd_dart_exit_stage(this.value);

  static sd_dart_exit_stage fromValue(int value) => switch (value) {
    0 => SD_DART_EXIT_STAGE_CONTEXT_USER,
    1 => SD_DART_EXIT_STAGE_CONTEXT,
    2 => SD_DART_EXIT_STAGE_RESOURCE,
    _ => throw ArgumentError('Unknown value for sd_dart_exit_stage: $value'),
  };
}

final class sd_dart_gpu_device_memory_t extends ffi.Struct {
  @ffi.Uint64()
  external int total_bytes;

  @ffi.Uint64()
  external int free_bytes;

  @ffi.Int32()
  external int type;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> description;
}

enum sd_dart_gpu_device_type {
  SD_DART_GPU_DEVICE_DISCRETE(1),
  SD_DART_GPU_DEVICE_INTEGRATED(2);

  final int value;
  const sd_dart_gpu_device_type(this.value);

  static sd_dart_gpu_device_type fromValue(int value) => switch (value) {
    1 => SD_DART_GPU_DEVICE_DISCRETE,
    2 => SD_DART_GPU_DEVICE_INTEGRATED,
    _ => throw ArgumentError(
      'Unknown value for sd_dart_gpu_device_type: $value',
    ),
  };
}

enum sd_dart_gpu_status {
  SD_DART_GPU_OK(0),
  SD_DART_GPU_INVALID_ARGUMENT(-1),
  SD_DART_GPU_NO_BACKEND(-2),
  SD_DART_GPU_NO_DEVICE(-3),
  SD_DART_GPU_UNAVAILABLE(-4);

  final int value;
  const sd_dart_gpu_status(this.value);

  static sd_dart_gpu_status fromValue(int value) => switch (value) {
    0 => SD_DART_GPU_OK,
    -1 => SD_DART_GPU_INVALID_ARGUMENT,
    -2 => SD_DART_GPU_NO_BACKEND,
    -3 => SD_DART_GPU_NO_DEVICE,
    -4 => SD_DART_GPU_UNAVAILABLE,
    _ => throw ArgumentError('Unknown value for sd_dart_gpu_status: $value'),
  };
}

final class sd_dart_progress_t extends ffi.Struct {
  @ffi.Uint64()
  external int sequence;

  @ffi.Int32()
  external int step;

  @ffi.Int32()
  external int steps;

  @ffi.Float()
  external double time;

  static ffi.Pointer<sd_dart_progress_t> $allocate(
    ffi.Allocator $allocator, {
    required int sequence,
    required int step,
    required int steps,
    required double time,
  }) => $allocator<sd_dart_progress_t>()
    ..ref.sequence = sequence
    ..ref.step = step
    ..ref.steps = steps
    ..ref.time = time;
}

final class sd_embedding_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Char> path;

  static ffi.Pointer<sd_embedding_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> name,
    required ffi.Pointer<ffi.Char> path,
  }) => $allocator<sd_embedding_t>()
    ..ref.name = name
    ..ref.path = path;
}

typedef sd_graph_eval_callback_t =
    ffi.Pointer<ffi.NativeFunction<sd_graph_eval_callback_tFunction>>;
typedef sd_graph_eval_callback_tFunction =
    ffi.Bool Function(
      ffi.Pointer<ggml_tensor> t,
      ffi.Bool ask,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef Dartsd_graph_eval_callback_tFunction =
    bool Function(
      ffi.Pointer<ggml_tensor> t,
      bool ask,
      ffi.Pointer<ffi.Void> user_data,
    );

final class sd_guidance_params_t extends ffi.Struct {
  @ffi.Float()
  external double txt_cfg;

  @ffi.Float()
  external double img_cfg;

  @ffi.Float()
  external double distilled_guidance;

  external sd_slg_params_t slg;
}

final class sd_hires_params_t extends ffi.Struct {
  @ffi.Bool()
  external bool enabled;

  @ffi.UnsignedInt()
  external int upscalerAsInt;

  sd_hires_upscaler_t get upscaler =>
      sd_hires_upscaler_t.fromValue(upscalerAsInt);
  set upscaler(sd_hires_upscaler_t value) => upscalerAsInt = value.value;

  external ffi.Pointer<ffi.Char> model_path;

  @ffi.Float()
  external double scale;

  @ffi.Int()
  external int target_width;

  @ffi.Int()
  external int target_height;

  @ffi.Int()
  external int steps;

  @ffi.Float()
  external double denoising_strength;

  @ffi.Int()
  external int upscale_tile_size;

  external ffi.Pointer<ffi.Float> custom_sigmas;

  @ffi.Int()
  external int custom_sigmas_count;

  static ffi.Pointer<sd_hires_params_t> $allocate(
    ffi.Allocator $allocator, {
    required bool enabled,
    required sd_hires_upscaler_t upscaler,
    required ffi.Pointer<ffi.Char> model_path,
    required double scale,
    required int target_width,
    required int target_height,
    required int steps,
    required double denoising_strength,
    required int upscale_tile_size,
    required ffi.Pointer<ffi.Float> custom_sigmas,
    required int custom_sigmas_count,
  }) => $allocator<sd_hires_params_t>()
    ..ref.enabled = enabled
    ..ref.upscaler = upscaler
    ..ref.model_path = model_path
    ..ref.scale = scale
    ..ref.target_width = target_width
    ..ref.target_height = target_height
    ..ref.steps = steps
    ..ref.denoising_strength = denoising_strength
    ..ref.upscale_tile_size = upscale_tile_size
    ..ref.custom_sigmas = custom_sigmas
    ..ref.custom_sigmas_count = custom_sigmas_count;
}

enum sd_hires_upscaler_t {
  SD_HIRES_UPSCALER_NONE(0),
  SD_HIRES_UPSCALER_LATENT(1),
  SD_HIRES_UPSCALER_LATENT_NEAREST(2),
  SD_HIRES_UPSCALER_LATENT_NEAREST_EXACT(3),
  SD_HIRES_UPSCALER_LATENT_ANTIALIASED(4),
  SD_HIRES_UPSCALER_LATENT_BICUBIC(5),
  SD_HIRES_UPSCALER_LATENT_BICUBIC_ANTIALIASED(6),
  SD_HIRES_UPSCALER_LANCZOS(7),
  SD_HIRES_UPSCALER_NEAREST(8),
  SD_HIRES_UPSCALER_MODEL(9),
  SD_HIRES_UPSCALER_COUNT(10);

  final int value;
  const sd_hires_upscaler_t(this.value);

  static sd_hires_upscaler_t fromValue(int value) => switch (value) {
    0 => SD_HIRES_UPSCALER_NONE,
    1 => SD_HIRES_UPSCALER_LATENT,
    2 => SD_HIRES_UPSCALER_LATENT_NEAREST,
    3 => SD_HIRES_UPSCALER_LATENT_NEAREST_EXACT,
    4 => SD_HIRES_UPSCALER_LATENT_ANTIALIASED,
    5 => SD_HIRES_UPSCALER_LATENT_BICUBIC,
    6 => SD_HIRES_UPSCALER_LATENT_BICUBIC_ANTIALIASED,
    7 => SD_HIRES_UPSCALER_LANCZOS,
    8 => SD_HIRES_UPSCALER_NEAREST,
    9 => SD_HIRES_UPSCALER_MODEL,
    10 => SD_HIRES_UPSCALER_COUNT,
    _ => throw ArgumentError('Unknown value for sd_hires_upscaler_t: $value'),
  };
}

final class sd_image_preprocess_params_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> rules;

  static ffi.Pointer<sd_image_preprocess_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> rules,
  }) => $allocator<sd_image_preprocess_params_t>()..ref.rules = rules;
}

final class sd_image_t extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int channel;

  external ffi.Pointer<ffi.Uint8> data;

  static ffi.Pointer<sd_image_t> $allocate(
    ffi.Allocator $allocator, {
    required int width,
    required int height,
    required int channel,
    required ffi.Pointer<ffi.Uint8> data,
  }) => $allocator<sd_image_t>()
    ..ref.width = width
    ..ref.height = height
    ..ref.channel = channel
    ..ref.data = data;
}

final class sd_img_gen_params_t extends ffi.Struct {
  external ffi.Pointer<sd_lora_t> loras;

  @ffi.Uint32()
  external int lora_count;

  external ffi.Pointer<ffi.Char> prompt;

  external ffi.Pointer<ffi.Char> negative_prompt;

  @ffi.Int()
  external int clip_skip;

  external sd_image_t init_image;

  external ffi.Pointer<sd_image_t> ref_images;

  @ffi.Int()
  external int ref_images_count;

  external ffi.Pointer<ffi.Char> ref_image_args;

  external sd_image_t mask_image;

  @ffi.Int()
  external int width;

  @ffi.Int()
  external int height;

  external sd_sample_params_t sample_params;

  @ffi.Float()
  external double strength;

  @ffi.Int64()
  external int seed;

  @ffi.Int()
  external int batch_count;

  external sd_image_t control_image;

  @ffi.Float()
  external double control_strength;

  external sd_image_t ip_adapter_image;

  @ffi.Float()
  external double ip_adapter_strength;

  external sd_pm_params_t pm_params;

  external sd_pulid_params_t pulid_params;

  external sd_tiling_params_t vae_tiling_params;

  external sd_cache_params_t cache;

  external sd_hires_params_t hires;

  @ffi.Int()
  external int qwen_image_layers;

  @ffi.Bool()
  external bool circular_x;

  @ffi.Bool()
  external bool circular_y;

  external sd_image_preprocess_params_t image_preprocess;
}

typedef sd_log_cb_t = ffi.Pointer<ffi.NativeFunction<sd_log_cb_tFunction>>;
typedef sd_log_cb_tFunction =
    ffi.Void Function(
      ffi.UnsignedInt level,
      ffi.Pointer<ffi.Char> text,
      ffi.Pointer<ffi.Void> data,
    );
typedef Dartsd_log_cb_tFunction =
    void Function(
      sd_log_level_t level,
      ffi.Pointer<ffi.Char> text,
      ffi.Pointer<ffi.Void> data,
    );

enum sd_log_level_t {
  SD_LOG_DEBUG(0),
  SD_LOG_VERBOSE(1),
  SD_LOG_INFO(2),
  SD_LOG_WARN(3),
  SD_LOG_ERROR(4);

  final int value;
  const sd_log_level_t(this.value);

  static sd_log_level_t fromValue(int value) => switch (value) {
    0 => SD_LOG_DEBUG,
    1 => SD_LOG_VERBOSE,
    2 => SD_LOG_INFO,
    3 => SD_LOG_WARN,
    4 => SD_LOG_ERROR,
    _ => throw ArgumentError('Unknown value for sd_log_level_t: $value'),
  };
}

final class sd_lora_t extends ffi.Struct {
  @ffi.Bool()
  external bool is_high_noise;

  @ffi.Float()
  external double multiplier;

  external ffi.Pointer<ffi.Char> path;

  static ffi.Pointer<sd_lora_t> $allocate(
    ffi.Allocator $allocator, {
    required bool is_high_noise,
    required double multiplier,
    required ffi.Pointer<ffi.Char> path,
  }) => $allocator<sd_lora_t>()
    ..ref.is_high_noise = is_high_noise
    ..ref.multiplier = multiplier
    ..ref.path = path;
}

final class sd_pm_params_t extends ffi.Struct {
  external ffi.Pointer<sd_image_t> id_images;

  @ffi.Int()
  external int id_images_count;

  external ffi.Pointer<ffi.Char> id_embed_path;

  @ffi.Float()
  external double style_strength;

  static ffi.Pointer<sd_pm_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<sd_image_t> id_images,
    required int id_images_count,
    required ffi.Pointer<ffi.Char> id_embed_path,
    required double style_strength,
  }) => $allocator<sd_pm_params_t>()
    ..ref.id_images = id_images
    ..ref.id_images_count = id_images_count
    ..ref.id_embed_path = id_embed_path
    ..ref.style_strength = style_strength;
}

typedef sd_preview_cb_t =
    ffi.Pointer<ffi.NativeFunction<sd_preview_cb_tFunction>>;
typedef sd_preview_cb_tFunction =
    ffi.Void Function(
      ffi.Int step,
      ffi.Int frame_count,
      ffi.Pointer<sd_image_t> frames,
      ffi.Bool is_noisy,
      ffi.Pointer<ffi.Void> data,
    );
typedef Dartsd_preview_cb_tFunction =
    void Function(
      int step,
      int frame_count,
      ffi.Pointer<sd_image_t> frames,
      bool is_noisy,
      ffi.Pointer<ffi.Void> data,
    );
typedef sd_progress_cb_t =
    ffi.Pointer<ffi.NativeFunction<sd_progress_cb_tFunction>>;
typedef sd_progress_cb_tFunction =
    ffi.Void Function(
      ffi.Int step,
      ffi.Int steps,
      ffi.Float time,
      ffi.Pointer<ffi.Void> data,
    );
typedef Dartsd_progress_cb_tFunction =
    void Function(int step, int steps, double time, ffi.Pointer<ffi.Void> data);

final class sd_pulid_params_t extends ffi.Struct {
  external ffi.Pointer<ffi.Char> id_embedding_path;

  @ffi.Float()
  external double id_weight;

  static ffi.Pointer<sd_pulid_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Char> id_embedding_path,
    required double id_weight,
  }) => $allocator<sd_pulid_params_t>()
    ..ref.id_embedding_path = id_embedding_path
    ..ref.id_weight = id_weight;
}

final class sd_ref_video_t extends ffi.Struct {
  external ffi.Pointer<sd_image_t> frames;

  @ffi.Int()
  external int frame_count;

  @ffi.Int()
  external int fps;

  external sd_audio_t audio;
}

final class sd_sample_params_t extends ffi.Struct {
  external sd_guidance_params_t guidance;

  @ffi.UnsignedInt()
  external int schedulerAsInt;

  scheduler_t get scheduler => scheduler_t.fromValue(schedulerAsInt);
  set scheduler(scheduler_t value) => schedulerAsInt = value.value;

  @ffi.UnsignedInt()
  external int sample_methodAsInt;

  sample_method_t get sample_method =>
      sample_method_t.fromValue(sample_methodAsInt);
  set sample_method(sample_method_t value) => sample_methodAsInt = value.value;

  @ffi.Int()
  external int sample_steps;

  @ffi.Float()
  external double eta;

  @ffi.Int()
  external int shifted_timestep;

  external ffi.Pointer<ffi.Float> custom_sigmas;

  @ffi.Int()
  external int custom_sigmas_count;

  @ffi.Float()
  external double flow_shift;

  external ffi.Pointer<ffi.Char> extra_sample_args;
}

final class sd_slg_params_t extends ffi.Struct {
  external ffi.Pointer<ffi.Int> layers;

  @ffi.Size()
  external int layer_count;

  @ffi.Float()
  external double layer_start;

  @ffi.Float()
  external double layer_end;

  @ffi.Float()
  external double scale;

  static ffi.Pointer<sd_slg_params_t> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Int> layers,
    required int layer_count,
    required double layer_start,
    required double layer_end,
    required double scale,
  }) => $allocator<sd_slg_params_t>()
    ..ref.layers = layers
    ..ref.layer_count = layer_count
    ..ref.layer_start = layer_start
    ..ref.layer_end = layer_end
    ..ref.scale = scale;
}

final class sd_tiling_params_t extends ffi.Struct {
  @ffi.Bool()
  external bool enabled;

  @ffi.Bool()
  external bool temporal_tiling;

  @ffi.Int()
  external int tile_size_w;

  @ffi.Int()
  external int tile_size_h;

  @ffi.Float()
  external double target_overlap;

  @ffi.Float()
  external double rel_size_w;

  @ffi.Float()
  external double rel_size_h;

  external ffi.Pointer<ffi.Char> extra_tiling_args;

  static ffi.Pointer<sd_tiling_params_t> $allocate(
    ffi.Allocator $allocator, {
    required bool enabled,
    required bool temporal_tiling,
    required int tile_size_w,
    required int tile_size_h,
    required double target_overlap,
    required double rel_size_w,
    required double rel_size_h,
    required ffi.Pointer<ffi.Char> extra_tiling_args,
  }) => $allocator<sd_tiling_params_t>()
    ..ref.enabled = enabled
    ..ref.temporal_tiling = temporal_tiling
    ..ref.tile_size_w = tile_size_w
    ..ref.tile_size_h = tile_size_h
    ..ref.target_overlap = target_overlap
    ..ref.rel_size_w = rel_size_w
    ..ref.rel_size_h = rel_size_h
    ..ref.extra_tiling_args = extra_tiling_args;
}

enum sd_type_t {
  SD_TYPE_F32(0),
  SD_TYPE_F16(1),
  SD_TYPE_Q4_0(2),
  SD_TYPE_Q4_1(3),
  SD_TYPE_Q5_0(6),
  SD_TYPE_Q5_1(7),
  SD_TYPE_Q8_0(8),
  SD_TYPE_Q8_1(9),
  SD_TYPE_Q2_K(10),
  SD_TYPE_Q3_K(11),
  SD_TYPE_Q4_K(12),
  SD_TYPE_Q5_K(13),
  SD_TYPE_Q6_K(14),
  SD_TYPE_Q8_K(15),
  SD_TYPE_IQ2_XXS(16),
  SD_TYPE_IQ2_XS(17),
  SD_TYPE_IQ3_XXS(18),
  SD_TYPE_IQ1_S(19),
  SD_TYPE_IQ4_NL(20),
  SD_TYPE_IQ3_S(21),
  SD_TYPE_IQ2_S(22),
  SD_TYPE_IQ4_XS(23),
  SD_TYPE_I8(24),
  SD_TYPE_I16(25),
  SD_TYPE_I32(26),
  SD_TYPE_I64(27),
  SD_TYPE_F64(28),
  SD_TYPE_IQ1_M(29),
  SD_TYPE_BF16(30),
  SD_TYPE_TQ1_0(34),
  SD_TYPE_TQ2_0(35),
  SD_TYPE_MXFP4(39),
  SD_TYPE_NVFP4(40),
  SD_TYPE_Q1_0(41),
  SD_TYPE_Q2_0(42),
  SD_TYPE_F8_E4M3(43),
  SD_TYPE_F8_E5M2(44),
  SD_TYPE_COUNT(45);

  final int value;
  const sd_type_t(this.value);

  static sd_type_t fromValue(int value) => switch (value) {
    0 => SD_TYPE_F32,
    1 => SD_TYPE_F16,
    2 => SD_TYPE_Q4_0,
    3 => SD_TYPE_Q4_1,
    6 => SD_TYPE_Q5_0,
    7 => SD_TYPE_Q5_1,
    8 => SD_TYPE_Q8_0,
    9 => SD_TYPE_Q8_1,
    10 => SD_TYPE_Q2_K,
    11 => SD_TYPE_Q3_K,
    12 => SD_TYPE_Q4_K,
    13 => SD_TYPE_Q5_K,
    14 => SD_TYPE_Q6_K,
    15 => SD_TYPE_Q8_K,
    16 => SD_TYPE_IQ2_XXS,
    17 => SD_TYPE_IQ2_XS,
    18 => SD_TYPE_IQ3_XXS,
    19 => SD_TYPE_IQ1_S,
    20 => SD_TYPE_IQ4_NL,
    21 => SD_TYPE_IQ3_S,
    22 => SD_TYPE_IQ2_S,
    23 => SD_TYPE_IQ4_XS,
    24 => SD_TYPE_I8,
    25 => SD_TYPE_I16,
    26 => SD_TYPE_I32,
    27 => SD_TYPE_I64,
    28 => SD_TYPE_F64,
    29 => SD_TYPE_IQ1_M,
    30 => SD_TYPE_BF16,
    34 => SD_TYPE_TQ1_0,
    35 => SD_TYPE_TQ2_0,
    39 => SD_TYPE_MXFP4,
    40 => SD_TYPE_NVFP4,
    41 => SD_TYPE_Q1_0,
    42 => SD_TYPE_Q2_0,
    43 => SD_TYPE_F8_E4M3,
    44 => SD_TYPE_F8_E5M2,
    45 => SD_TYPE_COUNT,
    _ => throw ArgumentError('Unknown value for sd_type_t: $value'),
  };
}

enum sd_vae_format_t {
  SD_VAE_FORMAT_AUTO(-1),
  SD_VAE_FORMAT_FLUX(0),
  SD_VAE_FORMAT_SD3(1),
  SD_VAE_FORMAT_FLUX2(2),
  SD_VAE_FORMAT_WAN(3),
  SD_VAE_FORMAT_COUNT(4);

  final int value;
  const sd_vae_format_t(this.value);

  static sd_vae_format_t fromValue(int value) => switch (value) {
    -1 => SD_VAE_FORMAT_AUTO,
    0 => SD_VAE_FORMAT_FLUX,
    1 => SD_VAE_FORMAT_SD3,
    2 => SD_VAE_FORMAT_FLUX2,
    3 => SD_VAE_FORMAT_WAN,
    4 => SD_VAE_FORMAT_COUNT,
    _ => throw ArgumentError('Unknown value for sd_vae_format_t: $value'),
  };
}

final class sd_vid_gen_params_t extends ffi.Struct {
  external ffi.Pointer<sd_lora_t> loras;

  @ffi.Uint32()
  external int lora_count;

  external ffi.Pointer<ffi.Char> prompt;

  external ffi.Pointer<ffi.Char> negative_prompt;

  @ffi.Int()
  external int clip_skip;

  external sd_image_t init_image;

  external sd_image_t end_image;

  external ffi.Pointer<sd_image_t> ref_images;

  @ffi.Int()
  external int ref_images_count;

  external ffi.Pointer<sd_ref_video_t> ref_videos;

  @ffi.Int()
  external int ref_videos_count;

  external ffi.Pointer<sd_audio_t> ref_audios;

  @ffi.Int()
  external int ref_audios_count;

  external ffi.Pointer<sd_image_t> control_frames;

  @ffi.Int()
  external int control_frames_size;

  @ffi.Int()
  external int width;

  @ffi.Int()
  external int height;

  external sd_sample_params_t sample_params;

  external sd_sample_params_t high_noise_sample_params;

  @ffi.Float()
  external double moe_boundary;

  @ffi.Float()
  external double strength;

  @ffi.Int64()
  external int seed;

  @ffi.Int()
  external int video_frames;

  @ffi.Int()
  external int fps;

  @ffi.Float()
  external double vace_strength;

  external sd_tiling_params_t vae_tiling_params;

  external sd_cache_params_t cache;

  external sd_hires_params_t hires;

  @ffi.Bool()
  external bool circular_x;

  @ffi.Bool()
  external bool circular_y;

  external sd_image_preprocess_params_t image_preprocess;
}

final class upscaler_ctx_t extends ffi.Opaque {}
