FROM ghcr.io/cirruslabs/flutter:stable

# Install Linux desktop build dependencies
RUN sudo apt-get update && sudo apt-get install -y \
  clang \
  cmake \
  ninja-build \
  pkg-config \
  libgtk-3-dev \
  libblkid-dev \
  liblzma-dev \
  libgl1-mesa-dri \
  mesa-utils \
  libvulkan-dev \
  glslc \
  nvidia-cuda-toolkit \
  && sudo rm -rf /var/lib/apt/lists/*

# Set up workspace
WORKDIR /app

# Mark as safe for git
RUN git config --global --add safe.directory /app
